---
- name: Reload Caddy
  service:
    name: caddy
    state: reloaded
  when: (caddy_config_mode | lower == 'caddyfile')

- name: Restart Caddy
  service:
    name: caddy
    state: restarted
  when: (caddy_config_mode | lower == 'json')