---
- name: Provision Bind9 DNS Server
  hosts: proxmox_dns

  roles:
    - update

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: [sudo, acl] # Used by dns configure playbook
        state: present

    - name: Create bind system group
      ansible.builtin.group:
        name: bind
        system: true
        state: present
      tags:
        - bind9

    - name: Create bind system user
      ansible.builtin.user:
        name: bind
        group: bind
        password: "!"
        shell: /usr/sbin/nologin
        home: /var/lib/bind
        create_home: false
        system: true
        state: present
      tags:
        - bind9

- name: Configure DNS
  ansible.builtin.import_playbook: configure_dns.yml
