---
- name: Provision Caddy Reverse Proxy
  hosts: HOME-PROXY-001

  roles:
    - role: update
    - role: caddy_server
      vars:
        caddy_server_caddy_config_mode: json
        caddy_server_caddy_plugins:
          - github.com/caddy-dns/cloudflare

- name: Configure Caddy
  import_playbook: configure_proxy.yml
