---
- name: Provision External Caddy Reverse Proxy
  hosts: EXT-PROXY-001

  roles:
    - role: update
    - role: hifis.toolkit.unattended_upgrades
    - role: caddy_server
      vars:
        caddy_server_caddy_config_mode: json
        caddy_server_caddy_plugins:
          - "github.com/caddy-dns/cloudflare"

- name: Configure Caddy
  import_playbook: configure_proxy.yml
