---
- name: Get latest Caddy version
  ansible.builtin.uri:
    url: https://api.github.com/repos/caddyserver/caddy/releases/latest
    return_content: true
  register: caddy_release

- name: Download Caddy
  ansible.builtin.get_url:
    url: >-
      https://github.com/caddyserver/caddy/releases/download/
      {{ caddy_release.json.tag_name }}/caddy_
      {{ caddy_release.json.tag_name | regex_replace("v", "") }}_
      {{ ansible_system | lower }}_{{ ansible_architecture | regex_replace("x86_64", "amd64") }}.tar.gz
    dest: /tmp/caddy.tar.gz
    mode: "0644"

- name: Extract Caddy
  ansible.builtin.unarchive:
    src: /tmp/caddy.tar.gz
    dest: /tmp
    remote_src: true

- name: Copy Caddy to /usr/bin/
  ansible.builtin.copy:
    src: /tmp/caddy
    dest: /usr/bin/caddy
    remote_src: true
    mode: "0755"

- name: Get installed Caddy Plugins
  ansible.builtin.command: caddy build-info
  register: caddy_build_info
  changed_when: false

- name: Install Caddy Plugins
  ansible.builtin.command: "caddy add-package {{ item }}"
  loop: "{{ caddy_plugins }}"
  when: item not in caddy_build_info.stdout
  changed_when: true

- name: Create Caddy system group
  ansible.builtin.group:
    name: caddy
    system: true
    state: present

- name: Create Caddy system user
  ansible.builtin.user:
    name: caddy
    group: caddy
    password: "!"
    shell: /usr/sbin/nologin
    home: /var/lib/caddy
    create_home: true
    system: true

- name: Set service template based on config format
  ansible.builtin.set_fact:
    caddy_service_template: >-
      {% if caddy_config_mode == "json" %}templates/caddy-api.service.j2{% else %}templates/caddy.service.j2{% endif %}

- name: Create Caddy systemd service file
  ansible.builtin.template:
    src: "{{ caddy_service_template }}"
    dest: /etc/systemd/system/caddy.service
    mode: "0644"

- name: Create default CaddyFile
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
    mode: "0644"
  notify:
    - Reload Caddy

- name: Enable Caddy service
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started
    daemon_reload: true
