---
- name: Configure Bind9
  hosts: proxmox_dns

  roles:
    - role: systemli.bind9
      vars:
        bind9_forward: true
        bind9_recursor: true
        bind9_authoritative: true
        bind9_generate_ddns_key: false

        internal_networks:
          - 192.168.0.0/16

        bind9_our_networks: "{{ internal_networks }}"

        bind9_forward_servers:
          - 9.9.9.9
          - 149.112.112.112

        bind9_zones_dynamic:
          - name: home.tinymagellanic.cloud
            type: master
            default_ttl: 1d
            primary: home.tinymagellanic.cloud
            admin: info.tinymagellanic.cloud
            serial: "{{'%Y%m%d01' | strftime }}"

            ns_records:
              - ns.home.tinymagellanic.cloud.

            rrs:
              - label: ns
                type: A
                rdata: 192.168.100.10
              - label: hypervisor1
                type: A
                rdata: 192.168.100.2
              - label: '*'
                type: A
                rdata: 192.168.100.20
  
  tasks:
    - name: Restrict allow-query to our_networks
      replace:
        path: /etc/bind/named.conf.options
        regexp: 'allow-query { any; };'
        replace: 'allow-query { our_networks; };'
      notify: Restart Bind9

  handlers:
    - name: Restart Bind9
      systemd:
        name: bind9
        state: restarted

