---
- name: Install Docker
  hosts: proxmox_docker, ml_servers
  become: yes
  gather_facts: yes

  vars:
    docker_users:
      - "{{ lookup('env', 'ANSIBLE_REMOTE_USER') }}"
    docker_install_compose_plugin: true
  
  roles:
    - geerlingguy.docker