---
- name: Install Docker
  hosts: proxmox_docker, ml_servers
  become: true
  gather_facts: true

  vars:
      docker_users:
          - "{{ lookup('env', 'ANSIBLE_REMOTE_USER') }}"
      docker_install_compose_plugin: true

  pre_tasks:
      - name: Ensure group "docker" exists with correct gid
        group:
            name: docker
            state: present
            gid: 989

  roles:
      - geerlingguy.docker
