---
collections:
  - name: community.general
  - name: community.proxmox
  - name: community.docker
  - name: bitwarden.secrets

roles:
  - name: geerlingguy.docker
    # This is a workaround until trixie support is upstreamed
    src: https://github.com/acieslewicz/ansible-role-docker.git
    version: trixie-support
