---
version: latest

backups_path: /var/komodo/backups

db_username: admin

timezone: America/Denver

#=-------------------------=#
#= Komodo Core Environment =#
#=-------------------------=#
title: Komodo
first_server: ""
disable_confirm_dialog: false

monitoring_interval: "15-sec"
resource_poll_interval: "1-hr"

webhook_secret: ""
jwt_secret: ""
jwt_ttl: "1-day"

init_admin_username: admin
init_admin_password: changeme

local_auth: false
disable_user_registration: false
enable_new_users: false
disable_non_admin_create: false
transparent_mode: false

logging_pretty: false
pretty_startup_config: false

#=-----------=#
#= OIDC Auth =#
#=-----------=#
oidc_enabled: false

#########
# OAUTH #
#########
google_oauth_enabled: false
github_oauth_enabled: false

###################
# CLOUD PROVIDERS #
###################
aws_access_key_id: ""
aws_secret_access_key: ""

#=------------------------------=#
#= Komodo Periphery Environment =#
#=------------------------------=#
periphery_root_directory: "/etc/komodo"
periphery_disable_terminals: false
periphery_ssl_enabled: true
periphery_include_disk_mounts: "/etc/hostname"
periphery_logging_pretty: false
periphery_pretty_startup_config: false
