---
version: 2

backups_path: /var/komodo/backups

timezone: America/Denver

#=-------------------------=#
#= Komodo Core Environment =#
#=-------------------------=#
title: Komodo
komodo_port: 9120
bind_ip: "[::]"

private_key: file:/config/keys/core.key

ui_write_disabled: false
disable_confirm_dialog: false
disable_websocket_reconnect: false
disable_init_resources: false

#=--------------=#
#= AUTH / LOGIN =#
#=--------------=#

local_auth: false
min_password_length: 1
init_admin_password: changeme 

disable_user_registration: false
enable_new_users: false
disable_non_admin_create: false
transparent_mode: false

jwt_secret: ""
jwt_ttl: "1-day"

#=-----------=#
#= OIDC Auth =#
#=-----------=#
oidc_enabled: false

#=-------=#
#= OAUTH =#
#=-------=#
google_oauth_enabled: false
github_oauth_enabled: false

#=---------------------=#
#= Auth Rate Limiting  =#
#=---------------------=#

auth_rate_limit_disabled: false
auth_rate_limit_max_attempts: 5
auth_rate_limit_window_seconds: 15

#=------------------=#
#= Poll Intervals   =#
#=------------------=#

monitoring_interval: "15-sec"
resource_poll_interval: "1-hr"

#=----------=#
#= DATABASE =#
#=----------=#

db_username: admin

#=-----------=#
#= Webhooks  =#
#=-----------=#

webhook_secret: ""
webhook_base_url: ""

#=---------=#
#= Logging =#
#=---------=#

logging_pretty: false
pretty_startup_config: false

#=-----------------=#
#= Cloud Providers =#
#=-----------------=#

aws_access_key_id: ""
aws_secret_access_key: ""

#=---------------=#
#= Git providers =#
#=---------------=#
git_providers: []

#=---------=#
#= Secrets =#
#=---------=#
komodo_secrets: {}
