name: WireGuard example

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    steps:
      - name: Setup wireguard
        run: |
            sudo apt install wireguard
            echo "${{ secrets.WIREGUARD_CONFIG }}" > wg0.conf
            sudo chmod 600 wg0.conf
            sudo wg-quick up ./wg0.conf
      
      - name: Ping test
        run: ping -c 4 192.168.100.2